services:
  relay-control-service:
    container_name: relay-control-service
    restart: always
    user: 2300:46
    image: oitc/acs.relay-control-service:latest
    # read_only needs to be false, because of write access to udev device
    read_only: false
    environment:
      MQTT_SERVER: test.mosquitto.org
      MQTT_PORT: 8883
      MQTT_TLS: true
      MQTT_CACERT_FILE: /etc/ssl/certs/ca-certificates.crt
      MQTT_TLS_INSECURE: false
      MQTT_CLIENT_ID: c27c9da3-ac39-47f2-bf03-48753d1ab3e7
      MQTT_USERNAME: acs.relay-control-service
      #MQTT_PASSWORD: myMQTTPassword
      MQTT_PASSWORD_FILE: /run/secrets/mqtt_password
      MQTT_TOPIC_DOOR_ACCESS: location/oitc-acs/entrypoints/+/access
      LDAP_SERVER: localhost
      LDAP_PORT: 389
      LDAP_TLS: false
      LDAP_USERDN: cn=myLdapUser,ou=users,dc=example,dc=org
      #LDAP_PASSWORD: myLDAPPassword
      LDAP_PASSWORD_FILE: /run/secrets/ldap_password
      LDAP_BASEDN: ou=Entry Points,ou=OITC Access Control System,dc=example,dc=org
      LDAP_FILTER: "(&(objectclass=ipHost)(objectclass=oitcACSAccessPointExtension)(ipHostNumber={entrypoint_ip}))"
      PROMETHEUS_LISTENER_ADDR: 0.0.0.0
      PROMETHEUS_LISTENER_PORT: 8080
      TZ: Europe/Berlin
    tmpfs:
      - /tmp
    volumes:
      - /srv/docker/acs.relay-control-service/etc/log4j2.xml:/app/etc/log4j2.xml:ro
    devices:
      - /dev/hidraw0:/dev/hidraw0
    ports:
      - "8080:8080"
    secrets:
      - mqtt_password
      - ldap_password

secrets:
  mqtt_password:
    file: /srv/docker/acs.relay-control-service/secrets/mqtt_password
  ldap_password:
    file: /srv/docker/acs.relay-control-service/secrets/ldap_password
