<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>de.oberdorf-itc.acs</groupId>
  <artifactId>relay-control-service</artifactId>
  <packaging>jar</packaging>
  <version>1.0.0</version>
  <name>${project.groupId}:${project.artifactId}</name>
  <url>https://www.oberdorf-itc.de/</url>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <jdk.version>25</jdk.version>
  </properties>
  <dependencies>
    <!-- Logging -->
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-core</artifactId>
      <version>2.25.4</version>
    </dependency>
    <dependency>
      <groupId>org.apache.logging.log4j</groupId>
      <artifactId>log4j-slf4j2-impl</artifactId>
      <version>2.25.4</version>
    </dependency>
    <!-- Dependent Libraries to listen to MQTT topics -->
    <!-- https://mvnrepository.com/artifact/org.eclipse.paho/org.eclipse.paho.client.mqttv3 -->
    <dependency>
      <groupId>org.eclipse.paho</groupId>
      <artifactId>org.eclipse.paho.client.mqttv3</artifactId>
      <version>1.2.5</version>
    </dependency>
    <dependency>
	    <groupId>net.java.dev.jna</groupId>
	    <artifactId>jna</artifactId>
	    <version>5.18.1</version>
	  </dependency>
    <!-- Dependencies related to Prometheus exporter-->
    <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>prometheus-metrics-core</artifactId>
      <version>1.5.1</version>
    </dependency>
    <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>prometheus-metrics-instrumentation-jvm</artifactId>
      <version>1.5.1</version>
    </dependency>
    <dependency>
      <groupId>io.prometheus</groupId>
      <artifactId>prometheus-metrics-exporter-httpserver</artifactId>
      <version>1.5.1</version>
    </dependency>
    <!-- To parse JSON objects -->
    <dependency>
      <groupId>com.google.code.gson</groupId>
      <artifactId>gson</artifactId>
      <version>2.13.2</version>
    </dependency>
    <dependency>
      <groupId>org.json</groupId>
      <artifactId>json</artifactId>
      <version>20251224</version>
    </dependency>
    <!-- LDAP handling -->
    <dependency>
      <groupId>com.unboundid</groupId>
      <artifactId>unboundid-ldapsdk-minimal-edition</artifactId>
      <version>3.2.1</version>
    </dependency>
    <!-- JUnit Tests -->
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <version>6.0.3</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <pluginManagement>
      <plugins>
        <plugin>
          <groupId>org.sonarsource.scanner.maven</groupId>
          <artifactId>sonar-maven-plugin</artifactId>
          <version>5.5.0.6356</version>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.15.0</version>
          <configuration>
            <source>${jdk.version}</source>
            <target>${jdk.version}</target>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.5.0</version>
          <configuration>
            <!-- https://maven.apache.org/shared/maven-archiver/ -->
            <archive>
              <addMavenDescriptor>false</addMavenDescriptor>
              <compress>true</compress>
              <forced>true</forced>
              <index>false</index>
              <manifest>
                <addClasspath>false</addClasspath>
                <addDefaultImplementationEntries>true</addDefaultImplementationEntries>
                <addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
                <addExtensions>false</addExtensions>
              </manifest>
            </archive>
          </configuration>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-source-plugin</artifactId>
          <version>3.4.0</version>
          <executions>
            <execution>
              <id>attach-sources</id>
              <goals>
                <goal>jar</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-javadoc-plugin</artifactId>
          <version>3.12.0</version>
          <executions>
            <execution>
              <id>attach-javadocs</id>
              <goals>
                <goal>jar</goal>
              </goals>
            </execution>
          </executions>
        </plugin>
        <plugin>
          <groupId>org.apache.maven.plugins</groupId>
          <artifactId>maven-gpg-plugin</artifactId>
          <version>3.2.8</version>
          <executions>
            <execution>
              <id>sign-artifacts</id>
              <phase>verify</phase>
              <goals>
                <goal>sign</goal>
              </goals>
              <configuration>
                <keyname>${gpg.keyname}</keyname>
                <passphraseServerId>${gpg.keyname}</passphraseServerId>
                <gpgArguments>
                  <arg>--pinentry-mode</arg>
                  <arg>loopback</arg>
                </gpgArguments>
              </configuration>
            </execution>
          </executions>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
  <organization>
    <name>Michael Oberdorf IT-Consulting</name>
    <url>https://www.oberdorf-itc.de/</url>
  </organization>
  <developers>
    <developer>
      <id>Cybcon</id>
      <name>Michael Oberdorf</name>
      <email>info@oberdorf-itc.de</email>
      <organization>Michael Oberdorf IT-Consulting</organization>
      <url>https://www.oberdorf-itc.de/</url>
      <organizationUrl>https://www.oberdorf-itc.de/</organizationUrl>
    </developer>
  </developers>
  <issueManagement >
  	<system>GitHub</system>
  	<url>https://github.com/oberdorf-itc/acs.relay-control-service/issues</url>
  </issueManagement>
  <scm>
    <connection>scm:git:https://github.com/oberdorf-itc/acs.relay-control-service.git</connection>
    <developerConnection>scm:git:ssh://git@github.com:oberdorf-itc/acs.relay-control-service.git</developerConnection>
    <url>https://github.com/oberdorf-itc/acs.relay-control-service</url>
  </scm>
  <ciManagement />
  <description>OITC Access Control System: service that controls the door relays.</description>
</project>
